### ISSUE TITLE
Add defaults for several properties of the UWG object

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/uwg-schema#5]
There are a lot of UWG model inputs that the vast majority of users will be unaware what constitutes a good default. There's also a good chance that people will usually want to run an annual sim and we can set the defaults accordingly.

It would be nice if we can add defaults for the following:

* "month": 1
* "day": 1
* "nday": 365
* "dtsim": 300
* "dtweather": 3600
* "autosize": false (does this variable even effect the simulation?)
* "sensocc": 100
* "latfocc": 0.3
* "radfocc": 0.2
* "radfequip": 0.5
* "radflight": 0.7
*  "h_ubl1": 1000
* "h_ubl2": 80
* "h_ref": 150
* "h_temp": 10
* "h_wind": 10
* "c_circ": 1.2
* "c_exch": 1
* "maxday": 150
* "maxnight": 20
* "windmin": 1
* "h_obs": 0.1
* "albveg": 0.25
* "rurvegcover": 0.9
* "latgrss": 0.4
* "lattree": 0.6

**Comment by saeranv** [comment]
@chriswmackey 

Sorry Chris, didn't see this. I'll add this today.
